version: "3.9"

services:

  db:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: "Password_123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-courses-system:/var/opt/mssql
    ports:
      # using the default port (1433) for sqlserver 
      - 1433:1433

  app:
    container_name: dotnet-courses-system
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
  
  # container for network troubleshooting
  net:
    container_name: net
    image: nicolaka/netshoot:latest

volumes:
  sqlserver-courses-system:
    name: sqlserver-courses-system
    external: true